/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#4edea3",
        "on-surface-variant": "#bdc8d1",
        "error-container": "#93000a",
        "surface-dim": "#0b1326",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary-container": "#8c0028",
        "on-primary-fixed-variant": "#004c69",
        "primary-container": "#38bdf8",
        "error": "#ffb4ab",
        "on-surface": "#dae2fd",
        "surface-bright": "#31394d",
        "tertiary-fixed-dim": "#ffb2b7",
        "tertiary-fixed": "#ffdadb",
        "surface-container-low": "#131b2e",
        "secondary": "#4edea3",
        "on-tertiary-fixed": "#40000d",
        "on-secondary-fixed-variant": "#005236",
        "background": "#0b1326",
        "primary": "#8ed5ff",
        "on-primary": "#00354a",
        "inverse-primary": "#00668a",
        "outline": "#87929a",
        "on-primary-container": "#004965",
        "on-secondary": "#003824",
        "surface-container-highest": "#2d3449",
        "on-tertiary-fixed-variant": "#92002a",
        "tertiary-container": "#ff929a",
        "inverse-on-surface": "#283044",
        "on-secondary-fixed": "#002113",
        "inverse-surface": "#dae2fd",
        "on-background": "#dae2fd",
        "on-tertiary": "#67001b",
        "secondary-container": "#00a572",
        "surface": "#0b1326",
        "primary-fixed-dim": "#7bd0ff",
        "primary-fixed": "#c4e7ff",
        "tertiary": "#ffbcbf",
        "outline-variant": "#3e484f",
        "on-error-container": "#ffdad6",
        "surface-container": "#171f33",
        "on-primary-fixed": "#001e2c",
        "surface-variant": "#2d3449",
        "surface-container-lowest": "#060e20",
        "on-secondary-container": "#00311f",
        "surface-container-high": "#222a3d",
        "on-error": "#690005",
        "surface-tint": "#7bd0ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
